# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\33 综合实践\数字图形图像\parking_roll_management_system\Form\ChargeStandard.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogChangeStandard(object):
    def setupUi(self, DialogChangeStandard):
        DialogChangeStandard.setObjectName("DialogChangeStandard")
        DialogChangeStandard.resize(550, 320)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(DialogChangeStandard)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 490, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setSpacing(16)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout_3.addWidget(self.lineEdit_1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(DialogChangeStandard)
        self.line.setGeometry(QtCore.QRect(30, 132, 491, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(DialogChangeStandard)
        self.line_4.setGeometry(QtCore.QRect(30, 252, 491, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(DialogChangeStandard)
        self.line_5.setGeometry(QtCore.QRect(20, 20, 20, 241))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(DialogChangeStandard)
        self.line_6.setGeometry(QtCore.QRect(510, 20, 20, 241))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(DialogChangeStandard)
        self.line_7.setGeometry(QtCore.QRect(30, 14, 491, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(DialogChangeStandard)
        self.line_8.setGeometry(QtCore.QRect(378, 20, 20, 121))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(DialogChangeStandard)
        self.line_9.setGeometry(QtCore.QRect(96, 20, 20, 120))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(DialogChangeStandard)
        self.line_10.setGeometry(QtCore.QRect(237, 20, 20, 120))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(DialogChangeStandard)
        self.line_11.setGeometry(QtCore.QRect(30, 73, 490, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.pushButtonOK = QtWidgets.QPushButton(DialogChangeStandard)
        self.pushButtonOK.setGeometry(QtCore.QRect(250, 270, 75, 23))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.label_10 = QtWidgets.QLabel(DialogChangeStandard)
        self.label_10.setGeometry(QtCore.QRect(30, 140, 491, 121))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(DialogChangeStandard)
        QtCore.QMetaObject.connectSlotsByName(DialogChangeStandard)
        DialogChangeStandard.setTabOrder(self.lineEdit_1, self.lineEdit_2)
        DialogChangeStandard.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        DialogChangeStandard.setTabOrder(self.lineEdit_3, self.pushButtonOK)

    def retranslateUi(self, DialogChangeStandard):
        _translate = QtCore.QCoreApplication.translate
        DialogChangeStandard.setWindowTitle(_translate("DialogChangeStandard", "收费标准"))
        self.label.setText(_translate("DialogChangeStandard", "车辆类别"))
        self.label_2.setText(_translate("DialogChangeStandard", "小型车"))
        self.label_7.setText(_translate("DialogChangeStandard", "1小时内"))
        self.label_8.setText(_translate("DialogChangeStandard", "大于1小时小于5小时\n"
"每小时"))
        self.lineEdit_1.setText(_translate("DialogChangeStandard", "5"))
        self.lineEdit_2.setText(_translate("DialogChangeStandard", "1"))
        self.lineEdit_3.setText(_translate("DialogChangeStandard", "4"))
        self.label_9.setText(_translate("DialogChangeStandard", "超过5小时\n"
"每小时"))
        self.pushButtonOK.setText(_translate("DialogChangeStandard", "确定"))
        self.label_10.setText(_translate("DialogChangeStandard", "1. 1小时内按1小时收费\n"
"2. 超过1小时的部分，不足1小时按一小时计费"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogChangeStandard = QtWidgets.QDialog()
    ui = Ui_DialogChangeStandard()
    ui.setupUi(DialogChangeStandard)
    DialogChangeStandard.show()
    sys.exit(app.exec_())
