# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\33 综合实践\数字图形图像\parking_roll_management_system\Form\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 549)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelLicensePlateNumber = QtWidgets.QLabel(self.centralwidget)
        self.labelLicensePlateNumber.setGeometry(QtCore.QRect(290, 390, 351, 67))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.labelLicensePlateNumber.setFont(font)
        self.labelLicensePlateNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelLicensePlateNumber.setMidLineWidth(6)
        self.labelLicensePlateNumber.setTextFormat(QtCore.Qt.AutoText)
        self.labelLicensePlateNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLicensePlateNumber.setObjectName("labelLicensePlateNumber")
        self.groupBoxCarPhoto = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxCarPhoto.setGeometry(QtCore.QRect(10, 10, 450, 370))
        self.groupBoxCarPhoto.setObjectName("groupBoxCarPhoto")
        self.labelCarPhote = QtWidgets.QLabel(self.groupBoxCarPhoto)
        self.labelCarPhote.setGeometry(QtCore.QRect(25, 30, 400, 300))
        self.labelCarPhote.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCarPhote.setObjectName("labelCarPhote")
        self.groupBoxGateAnimation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxGateAnimation.setGeometry(QtCore.QRect(470, 10, 450, 370))
        self.groupBoxGateAnimation.setObjectName("groupBoxGateAnimation")
        self.labelGateAnimation = QtWidgets.QLabel(self.groupBoxGateAnimation)
        self.labelGateAnimation.setGeometry(QtCore.QRect(25, 30, 400, 300))
        self.labelGateAnimation.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGateAnimation.setObjectName("labelGateAnimation")
        self.pushButtonEnter = QtWidgets.QPushButton(self.groupBoxGateAnimation)
        self.pushButtonEnter.setGeometry(QtCore.QRect(140, 340, 75, 23))
        self.pushButtonEnter.setObjectName("pushButtonEnter")
        self.pushButtonLeave = QtWidgets.QPushButton(self.groupBoxGateAnimation)
        self.pushButtonLeave.setGeometry(QtCore.QRect(230, 340, 75, 23))
        self.pushButtonLeave.setObjectName("pushButtonLeave")
        self.labelMessage = QtWidgets.QLabel(self.centralwidget)
        self.labelMessage.setGeometry(QtCore.QRect(230, 460, 471, 33))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.labelMessage.setFont(font)
        self.labelMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMessage.setObjectName("labelMessage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 23))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuQuery = QtWidgets.QMenu(self.menubar)
        self.menuQuery.setObjectName("menuQuery")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionChangeStandard = QtWidgets.QAction(MainWindow)
        self.actionChangeStandard.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionChangeStandard.setObjectName("actionChangeStandard")
        self.actionAutoBarrierControl = QtWidgets.QAction(MainWindow)
        self.actionAutoBarrierControl.setCheckable(True)
        self.actionAutoBarrierControl.setChecked(True)
        self.actionAutoBarrierControl.setObjectName("actionAutoBarrierControl")
        self.actionQueryStatistics = QtWidgets.QAction(MainWindow)
        self.actionQueryStatistics.setObjectName("actionQueryStatistics")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSimulateEnter = QtWidgets.QAction(MainWindow)
        self.actionSimulateEnter.setObjectName("actionSimulateEnter")
        self.actionSimulateLeave = QtWidgets.QAction(MainWindow)
        self.actionSimulateLeave.setObjectName("actionSimulateLeave")
        self.menuFile.addAction(self.actionSimulateEnter)
        self.menuFile.addAction(self.actionSimulateLeave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSetting.addAction(self.actionChangeStandard)
        self.menuSetting.addAction(self.actionAutoBarrierControl)
        self.menuQuery.addAction(self.actionQueryStatistics)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuQuery.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "停车场收费系统"))
        self.labelLicensePlateNumber.setText(_translate("MainWindow", "京A88888"))
        self.groupBoxCarPhoto.setTitle(_translate("MainWindow", "车辆照片"))
        self.labelCarPhote.setText(_translate("MainWindow", "车辆照片"))
        self.groupBoxGateAnimation.setTitle(_translate("MainWindow", "闸机动画"))
        self.labelGateAnimation.setText(_translate("MainWindow", "闸机动画"))
        self.pushButtonEnter.setText(_translate("MainWindow", "入库"))
        self.pushButtonLeave.setText(_translate("MainWindow", "出库"))
        self.labelMessage.setText(_translate("MainWindow", "共计停放0天2时30分，共计收费3元"))
        self.menuAbout.setTitle(_translate("MainWindow", "关于"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuSetting.setTitle(_translate("MainWindow", "设置"))
        self.menuQuery.setTitle(_translate("MainWindow", "查询"))
        self.actionQuit.setText(_translate("MainWindow", "退出"))
        self.actionChangeStandard.setText(_translate("MainWindow", "收费标准"))
        self.actionAutoBarrierControl.setText(_translate("MainWindow", "自动开闸"))
        self.actionQueryStatistics.setText(_translate("MainWindow", "查询统计"))
        self.actionPrint.setText(_translate("MainWindow", "打印"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionSimulateEnter.setText(_translate("MainWindow", "模拟进入"))
        self.actionSimulateLeave.setText(_translate("MainWindow", "模拟离开"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
