# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\33 综合实践\数字图形图像\parking_roll_management_system\Form\QueryStatistics.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogQueryStatistics(object):
    def setupUi(self, DialogQueryStatistics):
        DialogQueryStatistics.setObjectName("DialogQueryStatistics")
        DialogQueryStatistics.resize(450, 268)
        self.groupBoxQueryInput = QtWidgets.QGroupBox(DialogQueryStatistics)
        self.groupBoxQueryInput.setGeometry(QtCore.QRect(40, 20, 371, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.groupBoxQueryInput.setFont(font)
        self.groupBoxQueryInput.setObjectName("groupBoxQueryInput")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBoxQueryInput)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonRecent = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.radioButtonRecent.setFont(font)
        self.radioButtonRecent.setObjectName("radioButtonRecent")
        self.horizontalLayout_3.addWidget(self.radioButtonRecent)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditPeriodCount = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.lineEditPeriodCount.setFont(font)
        self.lineEditPeriodCount.setObjectName("lineEditPeriodCount")
        self.horizontalLayout_3.addWidget(self.lineEditPeriodCount)
        self.comboBoxPeriodType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.comboBoxPeriodType.setFont(font)
        self.comboBoxPeriodType.setCurrentText("")
        self.comboBoxPeriodType.setObjectName("comboBoxPeriodType")
        self.horizontalLayout_3.addWidget(self.comboBoxPeriodType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonPrevious = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonPrevious.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.radioButtonPrevious.setFont(font)
        self.radioButtonPrevious.setObjectName("radioButtonPrevious")
        self.horizontalLayout_2.addWidget(self.radioButtonPrevious)
        self.dateEditDateStart = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.dateEditDateStart.setFont(font)
        self.dateEditDateStart.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDateStart.setObjectName("dateEditDateStart")
        self.horizontalLayout_2.addWidget(self.dateEditDateStart)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dateEditDateEnd = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.dateEditDateEnd.setFont(font)
        self.dateEditDateEnd.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDateEnd.setObjectName("dateEditDateEnd")
        self.horizontalLayout_2.addWidget(self.dateEditDateEnd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBoxQueryOutput = QtWidgets.QGroupBox(DialogQueryStatistics)
        self.groupBoxQueryOutput.setGeometry(QtCore.QRect(40, 130, 371, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.groupBoxQueryOutput.setFont(font)
        self.groupBoxQueryOutput.setObjectName("groupBoxQueryOutput")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBoxQueryOutput)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 30, 311, 25))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(False)
        self.label_19.setIndent(-1)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_9.addWidget(self.label_19)
        self.lineEditVehicleTotalCount = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.lineEditVehicleTotalCount.setFont(font)
        self.lineEditVehicleTotalCount.setObjectName("lineEditVehicleTotalCount")
        self.horizontalLayout_9.addWidget(self.lineEditVehicleTotalCount)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.lineEditVehicleTotalCharge = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditVehicleTotalCharge.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.lineEditVehicleTotalCharge.setFont(font)
        self.lineEditVehicleTotalCharge.setObjectName("lineEditVehicleTotalCharge")
        self.horizontalLayout_9.addWidget(self.lineEditVehicleTotalCharge)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.pushButtonQuery = QtWidgets.QPushButton(DialogQueryStatistics)
        self.pushButtonQuery.setGeometry(QtCore.QRect(100, 230, 75, 23))
        self.pushButtonQuery.setObjectName("pushButtonQuery")
        self.pushButtonSave = QtWidgets.QPushButton(DialogQueryStatistics)
        self.pushButtonSave.setGeometry(QtCore.QRect(190, 230, 75, 23))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonPrint = QtWidgets.QPushButton(DialogQueryStatistics)
        self.pushButtonPrint.setGeometry(QtCore.QRect(280, 230, 75, 23))
        self.pushButtonPrint.setObjectName("pushButtonPrint")

        self.retranslateUi(DialogQueryStatistics)
        QtCore.QMetaObject.connectSlotsByName(DialogQueryStatistics)

    def retranslateUi(self, DialogQueryStatistics):
        _translate = QtCore.QCoreApplication.translate
        DialogQueryStatistics.setWindowTitle(_translate("DialogQueryStatistics", "查询统计"))
        self.groupBoxQueryInput.setTitle(_translate("DialogQueryStatistics", "统计时间输入"))
        self.radioButtonRecent.setText(_translate("DialogQueryStatistics", "近期"))
        self.label.setText(_translate("DialogQueryStatistics", "近"))
        self.radioButtonPrevious.setText(_translate("DialogQueryStatistics", "往期"))
        self.label_2.setText(_translate("DialogQueryStatistics", "至"))
        self.groupBoxQueryOutput.setTitle(_translate("DialogQueryStatistics", "统计结果"))
        self.label_19.setText(_translate("DialogQueryStatistics", "总计停放"))
        self.label_20.setText(_translate("DialogQueryStatistics", "辆，总计收费"))
        self.label_21.setText(_translate("DialogQueryStatistics", "元"))
        self.pushButtonQuery.setText(_translate("DialogQueryStatistics", "查询"))
        self.pushButtonSave.setText(_translate("DialogQueryStatistics", "保存记录"))
        self.pushButtonPrint.setText(_translate("DialogQueryStatistics", "打印记录"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogQueryStatistics = QtWidgets.QDialog()
    ui = Ui_DialogQueryStatistics()
    ui.setupUi(DialogQueryStatistics)
    DialogQueryStatistics.show()
    sys.exit(app.exec_())
